name: AutoDependabot

on:
  workflow_call:
    secrets:
          token:
            description: 'The GitHub Token which is used for the action bot'
            required: false

jobs:
  automerge:
    name: Auto-merge patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}